-- INSERT INTO users (username, password, gender, first_name, last_name, email, user_kind, enabled) VALUES ('admin', '$2a$10$rmX4HTXUJp5O2dY92zGRme/eoxsdkYDNb5kcdqb9WYeGqtFebvBSO', 'male', 'Super', 'Admin', 'admin@admin.com', 'super_admin', true);
-- INSERT INTO users (username, password, gender, first_name, last_name, email, user_kind, enabled) VALUES ('parentUser', '$2a$10$I9Y/2Bl/qEDgi/ObdJsmCeR0VeDtM2RUviLCwsNRVdadiTqyUUIga', 'male', 'Parent', 'User', 'parentUser@parentUser.com', 'parent', true);
-- INSERT INTO users (username, password, gender, first_name, last_name, email, user_kind, enabled, user_id) VALUES ('user', '$2a$10$I9Y/2Bl/qEDgi/ObdJsmCeR0VeDtM2RUviLCwsNRVdadiTqyUUIga', 'female', 'Subuser', '1', 'user@user.com', 'subuser', true, (SELECT id FROM users where username = 'parentUser'));
--
-- INSERT INTO groups (description, user_id) VALUES ('Birpin', (SELECT id FROM users WHERE username = 'admin'));
-- INSERT INTO groups (description, user_id) VALUES ('Empresa 1', (SELECT id FROM users WHERE username = 'parentUser'));
--
-- INSERT INTO roles (description, user_id) VALUES ('ROLE_ADMIN', (SELECT id FROM users WHERE username = 'parentUser'));
-- INSERT INTO roles (description, user_id) VALUES ('ROLE_USER', (SELECT id FROM users WHERE username = 'parentUser'));
--
-- INSERT INTO authorities (description) VALUES ('mcs1.action1.read');
-- INSERT INTO authorities (description) VALUES ('mcs1.action1.write');
-- INSERT INTO authorities (description) VALUES ('mcs1.action1.delete');
-- INSERT INTO authorities (description) VALUES ('mcs1.action2.read');
-- INSERT INTO authorities (description) VALUES ('mcs1.action2.write');
-- INSERT INTO authorities (description) VALUES ('mcs1.action2.delete');
-- INSERT INTO authorities (description) VALUES ('mcs2.action1.read');
-- INSERT INTO authorities (description) VALUES ('mcs2.action1.write');
-- INSERT INTO authorities (description) VALUES ('mcs2.action1.delete');
--
-- INSERT INTO authorities_roles (authority_id, role_id) VALUES ((SELECT id FROM authorities WHERE description = 'mcs1.action1.read'), (SELECT id FROM roles WHERE description = 'ROLE_ADMIN'));
-- INSERT INTO authorities_roles (authority_id, role_id) VALUES ((SELECT id FROM authorities WHERE description = 'mcs1.action1.write'), (SELECT id FROM roles WHERE description = 'ROLE_ADMIN'));
-- INSERT INTO authorities_roles (authority_id, role_id) VALUES ((SELECT id FROM authorities WHERE description = 'mcs1.action1.delete'), (SELECT id FROM roles WHERE description = 'ROLE_ADMIN'));
-- INSERT INTO authorities_roles (authority_id, role_id) VALUES ((SELECT id FROM authorities WHERE description = 'mcs1.action2.read'), (SELECT id FROM roles WHERE description = 'ROLE_ADMIN'));
-- INSERT INTO authorities_roles (authority_id, role_id) VALUES ((SELECT id FROM authorities WHERE description = 'mcs1.action2.write'), (SELECT id FROM roles WHERE description = 'ROLE_ADMIN'));
-- INSERT INTO authorities_roles (authority_id, role_id) VALUES ((SELECT id FROM authorities WHERE description = 'mcs1.action2.delete'), (SELECT id FROM roles WHERE description = 'ROLE_ADMIN'));
-- INSERT INTO authorities_roles (authority_id, role_id) VALUES ((SELECT id FROM authorities WHERE description = 'mcs2.action1.read'), (SELECT id FROM roles WHERE description = 'ROLE_ADMIN'));
-- INSERT INTO authorities_roles (authority_id, role_id) VALUES ((SELECT id FROM authorities WHERE description = 'mcs2.action1.write'), (SELECT id FROM roles WHERE description = 'ROLE_ADMIN'));
-- INSERT INTO authorities_roles (authority_id, role_id) VALUES ((SELECT id FROM authorities WHERE description = 'mcs2.action1.delete'), (SELECT id FROM roles WHERE description = 'ROLE_ADMIN'));
--
-- INSERT INTO authorities_roles (authority_id, role_id) VALUES ((SELECT id FROM authorities WHERE description = 'mcs1.action1.read'), (SELECT id FROM roles WHERE description = 'ROLE_USER'));
-- INSERT INTO authorities_roles (authority_id, role_id) VALUES ((SELECT id FROM authorities WHERE description = 'mcs1.action2.read'), (SELECT id FROM roles WHERE description = 'ROLE_USER'));
-- INSERT INTO authorities_roles (authority_id, role_id) VALUES ((SELECT id FROM authorities WHERE description = 'mcs2.action1.read'), (SELECT id FROM roles WHERE description = 'ROLE_USER'));
--
-- INSERT INTO roles_users (role_id, user_id) VALUES ((SELECT id FROM roles WHERE description = 'ROLE_USER'), (SELECT id FROM users WHERE username = 'user'));
-- INSERT INTO roles_users (role_id, user_id) VALUES ((SELECT id FROM roles WHERE description = 'ROLE_ADMIN'), (SELECT id FROM users WHERE username = 'parentUser'));
-- INSERT INTO roles_users (role_id, user_id) VALUES ((SELECT id FROM roles WHERE description = 'ROLE_USER'), (SELECT id FROM users WHERE username = 'parentUser'));
--
-- INSERT INTO groups_users (group_id, user_id) VALUES ((SELECT id FROM groups where description = 'Birpin'), (SELECT id FROM users WHERE username = 'admin'));
-- INSERT INTO groups_users (group_id, user_id) VALUES ((SELECT id FROM groups where description = 'Empresa 1'), (SELECT id FROM users WHERE username = 'parentUser'));
-- INSERT INTO groups_users (group_id, user_id) VALUES ((SELECT id FROM groups where description = 'Empresa 1'), (SELECT id FROM users WHERE username = 'user'));
